// <auto-generated/>
#nullable enable

namespace Capsule.Generated
{
    /// <summary>Every input driver this assembly declares. Generated code. Do not edit.</summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class CapsuleInputDrivers
    {
        internal static global::Capsule.Input.InputDriverRegistration[] Registrations { get; } =
            new global::Capsule.Input.InputDriverRegistration[]
            {
                new global::Capsule.Input.InputDriverRegistration("Walkthrough", static () => new global::Game.Walkthrough()),
            };
    }
}
