using System.Globalization;
using System.Text;

namespace Capsule.Build.Registry;

/// <summary>
/// The generated <c>CapsuleAssets</c> class, mirroring the folders under <c>Assets/</c>. Each file is
/// a member named for its file name and its type, as <c>player.png</c> declares <c>PlayerTexture</c>,
/// so files of two types share a name and a file may share its folder's. A misspelt asset is a
/// compile error and nothing is read at run time to learn what the build already measured.
/// </summary>
internal sealed class CapsuleAssetsFile
{
    internal const string FileName = "CapsuleAssets.g.cs";

    private readonly List<(Source Source, MemberWriter Write)> _declared = [];

    private readonly SortedSet<string> _beside = new(StringComparer.Ordinal);

    /// <summary>Declares <paramref name="source"/> as a member of its folder's class, written by <paramref name="write"/>.</summary>
    internal void Declare(Source source, MemberWriter write) => _declared.Add((source, write));

    /// <summary>Declares <paramref name="type"/> once beside <c>CapsuleAssets</c>, as a type its members use.</summary>
    internal void Beside(string type) => _beside.Add(type);

    /// <summary>
    /// The C# text, the same on every machine whatever order the sources were declared in, or null
    /// when a name is one C# would refuse.
    /// </summary>
    /// <param name="error">Receives each refusal, against the file that caused it.</param>
    internal string? Render(TextWriter error)
    {
        RegistryFolder root = new("CapsuleAssets", string.Empty);
        bool refused = false;

        foreach ((Source source, MemberWriter write) in _declared
            .OrderBy(static entry => entry.Source.Key, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Source.Type.Suffix, StringComparer.Ordinal))
        {
            string name = Generators.TypeNaming.ToIdentifier(source.Key[(source.Key.LastIndexOf('/') + 1)..]) + source.Type.Suffix;
            if (root.Add(source.Key, name, source.Path, write) is { } because)
            {
                error.WriteLine($"{source.Path}: is keyed \"{source.Key}\", {because}");
                refused = true;
            }
        }

        if (refused)
        {
            return null;
        }

        StringBuilder classes = new();
        root.Append(classes, "    ", "Every asset this game ships. Generated code. Do not edit.");
        foreach (string type in _beside)
        {
            classes.AppendLine().Append(type);
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace Capsule.Generated
            {
            {{classes}}}

            """;
    }
}

/// <summary>C# literals, the same on every machine whatever its culture.</summary>
internal static class Literal
{
    internal static string Of(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    internal static string Of(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>Round-trippable and suffixed, since an unsuffixed literal is a double a float parameter cannot take.</summary>
    internal static string Of(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "F";

    /// <summary>Round-trippable, so the constructor takes back the double the build measured.</summary>
    internal static string Of(double value) => Number(value) + "D";

    /// <summary>A number as a summary states it, unsuffixed.</summary>
    internal static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);
}
