using System.Globalization;
using System.Text;

namespace Capsule.Build.Sprites;

/// <summary>
/// Renders every sheet a game authors as one C# file the game compiles. Frames and clips become
/// typed members, so a misspelt frame or clip is a compile error and no document is read at run
/// time.
/// </summary>
public static class SpriteRegistrySource
{
    /// <summary>The generated class every sheet is declared on.</summary>
    public const string RegistryClass = "GameSprites";

    /// <summary>The generated class a sheet's frames are declared on.</summary>
    public const string FramesClass = "Frames";

    /// <summary>The generated class a sheet's clips are declared on.</summary>
    public const string ClipsClass = "Clips";

    private const string SpriteType = "global::Capsule.Rendering.Sprite";
    private const string RegionType = "global::Capsule.Rendering.TextureRegion";
    private const string TextureType = "global::Capsule.Assets.TextureHandle";
    private const string VectorType = "global::System.Numerics.Vector2";
    private const string ClipType = "global::Capsule.Animation.SpriteClip";

    /// <summary>
    /// The C# text declaring <paramref name="sheets"/>, ordered by sheet name so the output is the
    /// same on every machine whatever order the build collected the sources in.
    /// </summary>
    /// <param name="sheets">Each sheet's C# name paired with the document it was read from.</param>
    public static string Render(IReadOnlyList<(string Identifier, SpriteSheetDocument Document)> sheets)
    {
        ArgumentNullException.ThrowIfNull(sheets);

        List<(string Identifier, SpriteSheetDocument Document)> ordered = [.. sheets];
        ordered.Sort(static (left, right) => string.CompareOrdinal(left.Identifier, right.Identifier));

        StringBuilder source = new();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Capsule.Assets.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Every sprite sheet this game authors, as frames and clips. Generated; do not edit.</summary>");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        source.Append("    public static class ").AppendLine(RegistryClass);
        source.AppendLine("    {");

        for (int i = 0; i < ordered.Count; i++)
        {
            if (i > 0)
            {
                source.AppendLine();
            }

            AppendSheet(source, ordered[i].Identifier, ordered[i].Document);
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendSheet(StringBuilder source, string identifier, SpriteSheetDocument document)
    {
        string texture = $"new {TextureType}({Literal(document.Texture.Name)}, {Literal(document.Texture.Extension)})";

        source.Append("        /// <summary>The frames and clips cut from <c>")
            .Append(document.Texture.Name).Append(document.Texture.Extension).AppendLine("</c>.</summary>");
        source.Append("        public static class ").AppendLine(identifier);
        source.AppendLine("        {");

        source.AppendLine("            /// <summary>Every frame this sheet cuts, as sprites.</summary>");
        source.Append("            public static class ").AppendLine(FramesClass);
        source.AppendLine("            {");

        for (int i = 0; i < document.Frames.Count; i++)
        {
            SpriteSheetFrame frame = document.Frames[i];
            if (i > 0)
            {
                source.AppendLine();
            }

            source.Append("                /// <summary><c>").Append(frame.Name).Append("</c>: ")
                .Append(Number(frame.Region.Width)).Append('x').Append(Number(frame.Region.Height))
                .Append(" at (").Append(Number(frame.Region.X)).Append(", ").Append(Number(frame.Region.Y))
                .AppendLine(").</summary>");
            source.Append("                public static ").Append(SpriteType).Append(' ')
                .Append(Identifier(frame.Name)).Append(" => new ").Append(SpriteType).AppendLine("(");
            source.Append("                    ").Append(texture).AppendLine(",");
            source.Append("                    new ").Append(RegionType).Append('(')
                .Append(Number(frame.Region.X)).Append(", ").Append(Number(frame.Region.Y)).Append(", ")
                .Append(Number(frame.Region.Width)).Append(", ").Append(Number(frame.Region.Height)).AppendLine("),");
            source.Append("                    new ").Append(VectorType).Append('(')
                .Append(Number(frame.Pivot.X)).Append(", ").Append(Number(frame.Pivot.Y)).AppendLine("));");
        }

        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            /// <summary>Every clip this sheet plays over those frames.</summary>");
        source.Append("            public static class ").AppendLine(ClipsClass);
        source.AppendLine("            {");

        for (int i = 0; i < document.Clips.Count; i++)
        {
            SpriteSheetClip clip = document.Clips[i];
            if (i > 0)
            {
                source.AppendLine();
            }

            source.Append("                /// <summary><c>").Append(clip.Name).Append("</c>: ")
                .Append(Number(clip.Frames.Count)).Append(clip.Frames.Count == 1 ? " frame, " : " frames, ")
                .Append(Number(TotalTicks(clip))).Append(" ticks, ")
                .Append(clip.Loop ? "looping" : "played once").AppendLine(".</summary>");

            // A property with a field initializer, not an expression body: a clip is immutable and
            // shared, so every entity playing it reads one instance.
            source.Append("                public static ").Append(ClipType).Append(' ')
                .Append(Identifier(clip.Name)).Append(" { get; } = new ").Append(ClipType).AppendLine("(");
            source.Append("                    new ").Append(SpriteType).Append("[] { ");
            for (int j = 0; j < clip.Frames.Count; j++)
            {
                if (j > 0)
                {
                    source.Append(", ");
                }

                source.Append(FramesClass).Append('.').Append(Identifier(clip.Frames[j].Frame));
            }

            source.AppendLine(" },");
            source.Append("                    new int[] { ");
            for (int j = 0; j < clip.Frames.Count; j++)
            {
                if (j > 0)
                {
                    source.Append(", ");
                }

                source.Append(Number(clip.Frames[j].Ticks));
            }

            source.Append(" },").AppendLine();
            source.Append("                    ").Append(clip.Loop ? "true" : "false").AppendLine(");");
        }

        source.AppendLine("            }");
        source.AppendLine("        }");
    }

    private static int TotalTicks(SpriteSheetClip clip)
    {
        int total = 0;
        foreach (SpriteSheetClipFrame frame in clip.Frames)
        {
            total += frame.Ticks;
        }

        return total;
    }

    // The document has already been validated, so a name that is no identifier cannot reach here.
    private static string Identifier(string name) =>
        SpriteSheetNaming.ToIdentifier(name)!;

    private static string Number(int value) =>
        value.ToString(CultureInfo.InvariantCulture);

    // Round-trippable and suffixed: the pivot is a float, and an unsuffixed literal would be a
    // double the constructor cannot take.
    private static string Number(float value) =>
        value.ToString("R", CultureInfo.InvariantCulture) + "F";

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
