using System.Globalization;
using System.Text;
using Capsule.Generators;

namespace Capsule.Build.Sprites;

/// <summary>
/// Renders every sheet a game authors as one C# file the game compiles. Frames and clips become
/// typed members, so a misspelt frame or clip is a compile error and no document is read at run
/// time.
/// </summary>
internal static class SpriteRegistrySource
{
    /// <summary>The generated class every sheet is declared on.</summary>
    internal const string RegistryClass = "GameSprites";

    /// <summary>The generated class a sheet's frames are declared on.</summary>
    internal const string FramesClass = "Frames";

    /// <summary>The generated class a sheet's clips are declared on.</summary>
    internal const string ClipsClass = "Clips";

    private const string SpriteType = "global::Capsule.Rendering.Sprite";
    private const string RegionType = "global::Capsule.Rendering.TextureRegion";
    private const string TextureType = "global::Capsule.Assets.TextureHandle";
    private const string VectorType = "global::System.Numerics.Vector2";
    private const string ClipType = "global::Capsule.Animation.SpriteClip";

    /// <summary>
    /// The C# text declaring <paramref name="sheets"/>. A sheet's key is its path under the sprites
    /// root, and each directory in it becomes a nested class, so <c>enemies/bat</c> is declared as
    /// <c>GameSprites.Enemies.Bat</c>. Ordered by key so the output is the same on every machine
    /// whatever order the build collected the sources in.
    /// </summary>
    /// <param name="sheets">Each sheet's key paired with the document it was read from.</param>
    internal static string Render(IReadOnlyList<(string Key, SpriteSheetDocument Document)> sheets)
    {
        ArgumentNullException.ThrowIfNull(sheets);

        List<(string Key, SpriteSheetDocument Document)> ordered = [.. sheets];
        ordered.Sort(static (left, right) => string.CompareOrdinal(left.Key, right.Key));

        Node root = new(RegistryClass);
        foreach ((string key, SpriteSheetDocument document) in ordered)
        {
            Node node = root;
            string[] segments = key.Split('/');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                string identifier = Identifier(segments[i]);
                if (!node.Directories.TryGetValue(identifier, out Node? child))
                {
                    child = new Node(identifier);
                    node.Directories.Add(identifier, child);
                }

                node = child;
            }

            node.Sheets.Add(Identifier(segments[segments.Length - 1]), document);
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Capsule.Assets.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Every sprite sheet this game authors, as frames and clips. Generated; do not edit.</summary>");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");

        AppendDirectory(source, root, "    ", named: true);

        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendDirectory(StringBuilder source, Node node, string indent, bool named)
    {
        if (!named)
        {
            source.Append(indent).Append("/// <summary>The sheets authored under <c>").Append(node.Identifier)
                .AppendLine("</c>.</summary>");
        }

        source.Append(indent).Append("public static class ").AppendLine(node.Identifier);
        source.Append(indent).AppendLine("{");

        string inner = indent + "    ";
        bool first = true;

        foreach (KeyValuePair<string, SpriteSheetDocument> sheet in node.Sheets)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;
            AppendSheet(source, sheet.Key, sheet.Value, inner);
        }

        foreach (KeyValuePair<string, Node> directory in node.Directories)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;
            AppendDirectory(source, directory.Value, inner, named: false);
        }

        source.Append(indent).AppendLine("}");
    }

    private static void AppendSheet(StringBuilder source, string identifier, SpriteSheetDocument document, string indent)
    {
        string texture = $"new {TextureType}({Literal(document.Texture.Name)}, {Literal(document.Texture.Extension)})";
        string frames = indent + "    ";
        string member = frames + "    ";

        source.Append(indent).Append("/// <summary>The frames and clips cut from <c>")
            .Append(document.Texture.Name).Append(document.Texture.Extension).AppendLine("</c>.</summary>");
        source.Append(indent).Append("public static class ").AppendLine(identifier);
        source.Append(indent).AppendLine("{");

        source.Append(frames).AppendLine("/// <summary>Every frame this sheet cuts, as sprites.</summary>");
        source.Append(frames).Append("public static class ").AppendLine(FramesClass);
        source.Append(frames).AppendLine("{");

        for (int i = 0; i < document.Frames.Count; i++)
        {
            SpriteSheetFrame frame = document.Frames[i];
            if (i > 0)
            {
                source.AppendLine();
            }

            source.Append(member).Append("/// <summary><c>").Append(frame.Name).Append("</c>: ")
                .Append(Number(frame.Region.Width)).Append('x').Append(Number(frame.Region.Height))
                .Append(" at (").Append(Number(frame.Region.X)).Append(", ").Append(Number(frame.Region.Y))
                .AppendLine(").</summary>");
            source.Append(member).Append("public static ").Append(SpriteType).Append(' ')
                .Append(Identifier(frame.Name)).Append(" => new ").Append(SpriteType).AppendLine("(");
            source.Append(member).Append("    ").Append(texture).AppendLine(",");
            source.Append(member).Append("    new ").Append(RegionType).Append('(')
                .Append(Number(frame.Region.X)).Append(", ").Append(Number(frame.Region.Y)).Append(", ")
                .Append(Number(frame.Region.Width)).Append(", ").Append(Number(frame.Region.Height)).AppendLine("),");
            source.Append(member).Append("    new ").Append(VectorType).Append('(')
                .Append(Number(frame.Pivot.X)).Append(", ").Append(Number(frame.Pivot.Y)).AppendLine("));");
        }

        source.Append(frames).AppendLine("}");
        source.AppendLine();
        source.Append(frames).AppendLine("/// <summary>Every clip this sheet plays over those frames.</summary>");
        source.Append(frames).Append("public static class ").AppendLine(ClipsClass);
        source.Append(frames).AppendLine("{");

        for (int i = 0; i < document.Clips.Count; i++)
        {
            SpriteSheetClip clip = document.Clips[i];
            if (i > 0)
            {
                source.AppendLine();
            }

            source.Append(member).Append("/// <summary><c>").Append(clip.Name).Append("</c>: ")
                .Append(Number(clip.Frames.Count)).Append(clip.Frames.Count == 1 ? " frame, " : " frames, ")
                .Append(Number(TotalTicks(clip))).Append(" ticks, ")
                .Append(clip.Loop ? "looping" : "played once").AppendLine(".</summary>");

            // A property with a field initializer, not an expression body: a clip is immutable, so
            // every entity playing it reads one instance.
            source.Append(member).Append("public static ").Append(ClipType).Append(' ')
                .Append(Identifier(clip.Name)).Append(" { get; } = new ").Append(ClipType).AppendLine("(");
            source.Append(member).Append("    new ").Append(SpriteType).Append("[] { ");
            for (int j = 0; j < clip.Frames.Count; j++)
            {
                if (j > 0)
                {
                    source.Append(", ");
                }

                source.Append(FramesClass).Append('.').Append(Identifier(clip.Frames[j].Frame));
            }

            source.AppendLine(" },");
            source.Append(member).Append("    new int[] { ");
            for (int j = 0; j < clip.Frames.Count; j++)
            {
                if (j > 0)
                {
                    source.Append(", ");
                }

                source.Append(Number(clip.Frames[j].Ticks));
            }

            source.Append(" },").AppendLine();
            source.Append(member).Append("    ").Append(clip.Loop ? "true" : "false").AppendLine(");");
        }

        source.Append(frames).AppendLine("}");
        source.Append(indent).AppendLine("}");
    }

    private sealed class Node(string identifier)
    {
        internal string Identifier { get; } = identifier;

        internal SortedDictionary<string, SpriteSheetDocument> Sheets { get; } = new(StringComparer.Ordinal);

        internal SortedDictionary<string, Node> Directories { get; } = new(StringComparer.Ordinal);
    }

    private static int TotalTicks(SpriteSheetClip clip)
    {
        int total = 0;
        foreach (SpriteSheetClipFrame frame in clip.Frames)
        {
            total += frame.Ticks;
        }

        return total;
    }

    // The document has already been validated, so a name that is no identifier cannot reach here.
    private static string Identifier(string name) =>
        TypeNaming.ToIdentifier(name)!;

    private static string Number(int value) =>
        value.ToString(CultureInfo.InvariantCulture);

    // Round-trippable and suffixed: the pivot is a float, and an unsuffixed literal would be a
    // double the constructor cannot take.
    private static string Number(float value) =>
        value.ToString("R", CultureInfo.InvariantCulture) + "F";

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
