using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Generators;

// The text every generated registry file shares. Each renderer writes its own types into this frame.
internal static class GeneratedFile
{
    internal const string ExcludeFromCodeCoverage = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

    internal static void Add(SourceProductionContext context, string fileName, string text) =>
        context.AddSource(fileName, SourceText.From(text, Encoding.UTF8));

    internal static void Report(SourceProductionContext context, EquatableArray<Diagnostic> diagnostics)
    {
        foreach (Diagnostic diagnostic in diagnostics.Items)
        {
            context.ReportDiagnostic(diagnostic);
        }
    }

    /// <summary>A whole generated file: the header, the assembly attributes, then the types in <c>Capsule.Generated</c>.</summary>
    /// <param name="types">The namespace's body, indented one level, with no trailing newline.</param>
    internal static string Write(IReadOnlyCollection<string> assemblyAttributes, string types) => $$"""
        // <auto-generated/>
        #nullable enable

        {{AssemblyAttributes(assemblyAttributes)}}namespace Capsule.Generated
        {
        {{types}}
        }

        """;

    /// <summary>The <c>Registrations</c> array a registry class holds, one entry per line, with no trailing newline.</summary>
    /// <param name="entries">Each registration expression, whose continuation lines carry their own indent.</param>
    internal static string Registrations(string registrationType, IEnumerable<string> entries) => $$"""
                internal static {{registrationType}}[] Registrations { get; } =
                    new {{registrationType}}[]
                    {
        {{string.Concat(entries.Select(static entry => "                " + entry + ",\n"))}}            };
        """;

    /// <summary>The assembly attribute a logic assembly records one claimed key with, for the shell to check.</summary>
    internal static string ClaimAttribute(RegistryClaimKind kind, string key, string qualifiedType) =>
        $"[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute({(int)kind}, {CodeText.Literal(key)}, typeof({qualifiedType}))]";

    // One line each, then a blank line before the namespace.
    private static string AssemblyAttributes(IReadOnlyCollection<string> attributes) =>
        attributes.Count == 0 ? string.Empty : string.Concat(attributes.Select(static attribute => attribute + "\n")) + "\n";
}
