using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Capsule.Generators;

// The generated applier writes an [Authorable] field through an [UnsafeAccessor] no analysis sees. Two warnings
// about such a field are then wrong, and each needs its own mechanism. This suppressor quiets the compiler's
// never-assigned warning, which no attribute reaches. The advice to make the field readonly is suppressed by
// the attributes ReadonlySuppressions writes, because dotnet format applies that advice and ignores a suppressor.
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class AuthorableSuppressor : DiagnosticSuppressor
{
    public const string UnassignedFieldId = "CAP108";

    private static readonly SuppressionDescriptor Unassigned = new(
        UnassignedFieldId, "CS0649", "A scene document placement writes this [Authorable] field.");

    public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions => [Unassigned];

    public override void ReportSuppressions(SuppressionAnalysisContext context)
    {
        INamedTypeSymbol? authorable = context.Compilation.GetTypeByMetadataName(Symbols.AuthorableAttribute);
        if (authorable is null)
        {
            return;
        }

        foreach (Diagnostic diagnostic in context.ReportedDiagnostics)
        {
            if (diagnostic.Location.SourceTree is not { } tree)
            {
                continue;
            }

            VariableDeclaratorSyntax? declarator = tree.GetRoot(context.CancellationToken)
                .FindNode(diagnostic.Location.SourceSpan)
                .AncestorsAndSelf()
                .OfType<VariableDeclaratorSyntax>()
                .FirstOrDefault();
            if (declarator is not null
                && context.GetSemanticModel(tree).GetDeclaredSymbol(declarator, context.CancellationToken) is IFieldSymbol field
                && field.GetAttributes().Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, authorable)))
            {
                context.ReportSuppression(Suppression.Create(Unassigned, diagnostic));
            }
        }
    }

    /// <summary>The generated source suppressing the readonly advice on each field, by documentation id.</summary>
    internal static string ReadonlySuppressions(ImmutableArray<string> fields) =>
        "// <auto-generated/>\n" + string.Concat(fields.OrderBy(static id => id, StringComparer.Ordinal).Select(static id =>
            "[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Style\", \"IDE0044\", "
            + $"Justification = \"A scene document placement writes this [Authorable] field.\", Scope = \"member\", Target = \"~{id}\")]\n"));
}
