using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Generators;

/// <summary>One class the driver registry considered, and the name <c>--driver</c> reaches it by.</summary>
/// <param name="TypeName">The simple class name, which is the key <c>--driver</c> takes.</param>
/// <param name="At">Where a fault about this model is reported.</param>
internal readonly record struct InputDriverModel(
    string QualifiedName,
    string DisplayName,
    string TypeName,
    bool Accessible,
    DeclaredAt At);

internal static class InputDriverRegistrySource
{
    private const string FileName = "CapsuleInputDrivers.g.cs";

    internal static InputDriverModel? Describe(INamedTypeSymbol type, TypeDeclarationSyntax declaration, Compilation compilation)
    {
        // The generated registry constructs a driver the command line names. A driver that takes
        // arguments is left unregistered and reaches a run through WithInputDriver.
        if (!Symbols.IsConcreteClass(type)
            || !Symbols.HasPublicParameterlessConstructor(type)
            || !Symbols.Implements(type, compilation, Symbols.InputDriver))
        {
            return null;
        }

        return new InputDriverModel(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.ToDisplayString(),
            type.Name,
            Symbols.IsAccessibleFromGeneratedCode(type),
            DeclaredAt.From(declaration.Identifier.GetLocation()));
    }

    internal static void Emit(SourceProductionContext context, ImmutableArray<InputDriverModel> models, bool registered)
    {
        if (registered)
        {
            context.AddSource(FileName, SourceText.From(Render(Sound(context, models)), Encoding.UTF8));
        }
    }

    // Every driver the assembly registers, in declaration order. Each entry is accessible to
    // generated code and claims a name unused by another class. Names are claimed in this pass so
    // the registry keeps declaration order.
    internal static List<InputDriverModel> Sound(SourceProductionContext context, ImmutableArray<InputDriverModel> models)
    {
        List<InputDriverModel> sound = [];
        Dictionary<string, InputDriverModel> claimed = new(StringComparer.Ordinal);

        RegistryPass.Sound(
            context,
            models,
            static model => model.QualifiedName,
            static model => model.DisplayName,
            static model => model.At,
            static model => model.Accessible ? null : RegistryDiagnostics.InaccessibleRegisteredType,
            model =>
            {
                if (claimed.TryGetValue(model.TypeName, out InputDriverModel previous))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        RegistryDiagnostics.DuplicateInputDriverName,
                        model.At.Location(),
                        previous.DisplayName,
                        model.DisplayName,
                        model.TypeName));

                    return;
                }

                claimed.Add(model.TypeName, model);
                sound.Add(model);
            });

        return sound;
    }

    // One registration's construction, written the same way in the shell's entry point and in a
    // logic assembly's registry.
    internal static void AppendRegistration(StringBuilder source, InputDriverModel model)
    {
        source.Append("new global::Capsule.Input.InputDriverRegistration(");
        source.Append(SymbolDisplay.FormatLiteral(model.TypeName, quote: true));
        source.Append(", static () => new ");
        source.Append(model.QualifiedName);
        source.Append("())");
    }

    private static string Render(List<InputDriverModel> registered)
    {
        StringBuilder registrations = new();

        foreach (InputDriverModel model in registered)
        {
            registrations.Append("                ");
            AppendRegistration(registrations, model);
            registrations.AppendLine(",");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace Capsule.Scenes.Generated
            {
                /// <summary>Every input driver this assembly declares. Generated code. Do not edit.</summary>
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal static class CapsuleInputDrivers
                {
                    internal static global::Capsule.Input.InputDriverRegistration[] Registrations { get; } =
                        new global::Capsule.Input.InputDriverRegistration[]
                        {
            {{registrations}}            };
                }
            }

            """;
    }
}
