using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Generators;

internal static class RegistryProviderSource
{
    private const string FileName = "CapsuleRegistryProvider.g.cs";

    internal static void Emit(SourceProductionContext context, string? providerName)
    {
        if (providerName is not null)
        {
            context.AddSource(FileName, SourceText.From(Render(providerName), Encoding.UTF8));
        }
    }

    // The provider an assembly is reached through, plus the two attributes a shell reads its
    // registry metadata from. Only generated code calls these members.
    private static string Render(string providerName) => $$"""
        // <auto-generated/>
        #nullable enable

        [assembly: global::Capsule.Scenes.Generated.CapsuleGeneratedRegistryProviderAttribute(typeof(global::Capsule.Scenes.Generated.{{providerName}}))]

        namespace Capsule.Scenes.Generated
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class CapsuleGeneratedRegistryProviderAttribute : global::System.Attribute
            {
                public CapsuleGeneratedRegistryProviderAttribute(global::System.Type providerType) => ProviderType = providerType;
                public global::System.Type ProviderType { get; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class CapsuleGeneratedRegistryClaimAttribute : global::System.Attribute
            {
                public CapsuleGeneratedRegistryClaimAttribute(int kind, string key, global::System.Type declaringType)
                {
                    Kind = kind;
                    Key = key;
                    DeclaringType = declaringType;
                }
                public int Kind { get; }
                public string Key { get; }
                public global::System.Type DeclaringType { get; }
            }

            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            public static class {{providerName}}
            {
                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static void AddEntities(global::System.Collections.Generic.List<global::Capsule.Scenes.Spawning.EntityRegistration> registrations)
                {
                    global::System.ArgumentNullException.ThrowIfNull(registrations);
                    registrations.AddRange(global::Capsule.Scenes.Generated.CapsuleEntities.Registrations);
                }

                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static void AddScenes(global::System.Collections.Generic.List<global::Capsule.Scenes.SceneRegistration> registrations)
                {
                    global::System.ArgumentNullException.ThrowIfNull(registrations);
                    registrations.AddRange(global::Capsule.Scenes.Generated.CapsuleScenes.Registrations);
                }

                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                public static void AddDrivers(global::System.Collections.Generic.List<global::Capsule.Input.InputDriverRegistration> registrations)
                {
                    global::System.ArgumentNullException.ThrowIfNull(registrations);
                    registrations.AddRange(global::Capsule.Scenes.Generated.CapsuleInputDrivers.Registrations);
                }
            }
        }

        """;
}
