using System.Globalization;
using System.Text;
using Capsule.Audio;
using Capsule.Generators;

namespace Capsule.Build.Audio;

/// <summary>
/// Renders every audio source a game ships as one C# file the game compiles. Each clip becomes a
/// typed member carrying the duration the build measured, so a misspelt clip is a compile error and
/// no file is read at run time to learn how long a sound is.
/// </summary>
internal static class AudioRegistrySource
{
    /// <summary>The generated class the asset registry and every domain share.</summary>
    internal const string RootClass = "CapsuleAssets";

    /// <summary>The generated class every clip is declared under.</summary>
    internal const string RegistryClass = "Audio";

    /// <summary>The set member every generated class carries, and therefore a name no clip may take.</summary>
    internal const string ListMember = "All";

    private const string ClipType = "global::Capsule.Audio.AudioClip";

    private const string RegionType = "global::Capsule.Audio.AudioLoopRegion";

    private const string BackingField = "_all";

    /// <summary>
    /// The C# text declaring <paramref name="clips"/>. A clip's key is its path under the audio
    /// root, and each directory in it becomes a nested class, so <c>steps/stone</c> is declared as
    /// <c>CapsuleAssets.Audio.Steps.Stone</c>. Ordered by key so the output is the same on every
    /// machine whatever order the build collected the sources in.
    /// </summary>
    /// <param name="clips">Each clip's key paired with the extension and duration measured for it.</param>
    internal static string Render(IReadOnlyList<AudioSourceClip> clips)
    {
        ArgumentNullException.ThrowIfNull(clips);

        List<AudioSourceClip> ordered = [.. clips];
        ordered.Sort(static (left, right) => string.CompareOrdinal(left.Key, right.Key));

        Node root = new(RegistryClass, string.Empty);
        foreach (AudioSourceClip clip in ordered)
        {
            Node node = root;
            string[] segments = clip.Key.Split('/');

            // A directory is a set, and its subdirectories are in it.
            root.All.Add(clip);

            for (int i = 0; i < segments.Length - 1; i++)
            {
                string identifier = Identifier(segments[i]);
                if (!node.Directories.TryGetValue(identifier, out Node? child))
                {
                    child = new Node(identifier, node.Display + segments[i] + "/");
                    node.Directories.Add(identifier, child);
                }

                node = child;
                node.All.Add(clip);
            }

            node.Clips.Add(Identifier(segments[segments.Length - 1]), clip);
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Capsule.Assets.Generated");
        source.AppendLine("{");

        // The asset and sprite halves of this class carry the same summary, so whichever the
        // compiler keeps is the same text, and each half attributes only the classes it declares: a
        // non-repeatable attribute named by two halves of one partial class is CS0579.
        source.AppendLine("    /// <summary>Every asset this game ships and every sprite sheet it authors. Generated; do not edit.</summary>");
        source.Append("    public static partial class ").AppendLine(RootClass);
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>Every audio clip this game ships, with the duration the build measured for it.</summary>");
        source.AppendLine("        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");

        AppendDirectory(source, root, "        ");

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendDirectory(StringBuilder source, Node node, string indent)
    {
        string shipped = "assets/audio" + (node.Display.Length == 0 ? string.Empty : "/" + node.Display[..^1]);

        source.Append(indent).Append("public static class ").AppendLine(node.Identifier);
        source.Append(indent).AppendLine("{");

        string inner = indent + "    ";
        bool first = true;

        foreach (KeyValuePair<string, AudioSourceClip> clip in node.Clips)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;

            AudioLoopRegion loop = clip.Value.Loop;

            source.Append(inner).Append("/// <summary><c>audio/").Append(clip.Value.Key).Append(clip.Value.Extension)
                .Append("</c>, ").Append(Number(clip.Value.DurationSeconds)).Append(" seconds long");

            if (loop.HasRegion)
            {
                source.Append(", looping ").Append(Number(loop.StartSeconds)).Append(" to ")
                    .Append(Number(loop.EndSeconds)).Append(" seconds");
            }

            source.AppendLine(".</summary>");
            source.Append(inner).Append("public static ").Append(ClipType).Append(' ').Append(clip.Key)
                .Append(" => new ").Append(ClipType).Append('(');
            source.Append(Literal(clip.Value.Key)).Append(", ").Append(Literal(clip.Value.Extension)).Append(", ")
                .Append(Number(clip.Value.DurationSeconds)).Append('D');

            // Omitted where the source authored none, so a clip with no region renders exactly as it
            // did before regions existed and the constructor's own default stands.
            if (loop.HasRegion)
            {
                source.Append(", new ").Append(RegionType).Append('(').Append(Number(loop.StartSeconds))
                    .Append("D, ").Append(Number(loop.EndSeconds)).Append("D)");
            }

            source.AppendLine(");");
        }

        foreach (KeyValuePair<string, Node> directory in node.Directories)
        {
            if (!first)
            {
                source.AppendLine();
            }

            first = false;

            source.Append(inner).Append("/// <summary>Everything shipped at <c>assets/audio/")
                .Append(directory.Value.Display[..^1]).AppendLine("</c>.</summary>");
            AppendDirectory(source, directory.Value, inner);
        }

        AppendList(source, node, shipped, inner, first);

        source.Append(indent).AppendLine("}");
    }

    // Backed by a field and handed out as a span: allocation-free to enumerate, and read-only.
    private static void AppendList(StringBuilder source, Node node, string shipped, string indent, bool first)
    {
        if (!first)
        {
            source.AppendLine();
        }

        source.Append(indent).Append("private static readonly ").Append(ClipType).Append("[] ").Append(BackingField)
            .AppendLine(" =");
        source.Append(indent).Append("    new ").Append(ClipType).AppendLine("[]");
        source.Append(indent).AppendLine("    {");

        foreach (AudioSourceClip clip in node.All)
        {
            source.Append(indent).Append("        ").Append(Reference(node, clip)).AppendLine(",");
        }

        source.Append(indent).AppendLine("    };");
        source.AppendLine();
        source.Append(indent).Append("/// <summary>Every clip shipped under <c>").Append(shipped)
            .AppendLine("</c>, its subdirectories included.</summary>");
        source.Append(indent).Append("public static global::System.ReadOnlySpan<").Append(ClipType).Append("> ")
            .Append(ListMember).Append(" => ").Append(BackingField).AppendLine(";");
    }

    // How the clip is named from inside this class.
    private static string Reference(Node node, AudioSourceClip clip)
    {
        StringBuilder reference = new();

        foreach (string segment in clip.Key[node.Display.Length..].Split('/'))
        {
            if (reference.Length > 0)
            {
                reference.Append('.');
            }

            reference.Append(Identifier(segment));
        }

        return reference.ToString();
    }

    // The key has already been declared through AudioNames, so a segment that is no identifier
    // cannot reach here.
    private static string Identifier(string segment) => TypeNaming.ToIdentifier(segment)!;

    // Round-trippable and invariant: the same text on every machine, and a literal the AudioClip
    // constructor takes as the double it was measured as.
    private static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private sealed class Node(string identifier, string display)
    {
        internal string Identifier { get; } = identifier;

        // The source directory this class stands for, relative to the audio root and ending in a
        // separator; empty at the root.
        internal string Display { get; } = display;

        internal SortedDictionary<string, AudioSourceClip> Clips { get; } = new(StringComparer.Ordinal);

        internal SortedDictionary<string, Node> Directories { get; } = new(StringComparer.Ordinal);

        // Every clip beneath this class, transitively, in ordinal key order.
        internal List<AudioSourceClip> All { get; } = [];
    }
}
