using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Capsule.Generators;

// Writes CapsuleAuthorable.g.cs, which suppresses the advice to make a writable [Authorable] field readonly.
// AuthorableSuppressor explains why this is an attribute and not a suppressor. Entities/CapsuleAuthorable.sample.g.cs
// shows the file.
internal static class AuthorableSuppressionRenderer
{
    private const string FileName = "CapsuleAuthorable.g.cs";

    /// <summary>The documentation id of a writable instance [Authorable] field, or null for any other member.</summary>
    internal static string? Describe(GeneratorAttributeSyntaxContext marked) =>
        marked.TargetSymbol is IFieldSymbol { IsReadOnly: false, IsStatic: false } field
            ? field.GetDocumentationCommentId()
            : null;

    internal static void Emit(SourceProductionContext context, EquatableArray<string> fields)
    {
        if (fields.Items.Length > 0)
        {
            GeneratedFile.Add(context, FileName, Render(fields.Items));
        }
    }

    internal static string Render(ImmutableArray<string> fields) =>
        "// <auto-generated/>\n" + string.Concat(fields.OrderBy(static id => id, StringComparer.Ordinal).Select(static id =>
            "[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Style\", \"IDE0044\", "
            + $"Justification = \"A scene document placement writes this [Authorable] field.\", Scope = \"member\", Target = \"~{id}\")]\n"));
}
