// <auto-generated/>
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0044", Justification = "A scene document placement writes this [Authorable] field.", Scope = "member", Target = "~F:Game.Lamp._charge")]
