// <auto-generated/>
#nullable enable

[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute(0, "door", typeof(global::Game.Door))]
[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute(0, "floor-switch", typeof(global::Game.FloorSwitch))]
[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute(0, "lamp", typeof(global::Game.Lamp))]

namespace Capsule.Generated
{
    /// <summary>Every spawnable entity this assembly declares, as one registry. Generated code. Do not edit.</summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CapsuleEntities
    {
        internal static global::Capsule.Scenes.Spawning.EntityRegistration[] Registrations { get; } =
            new global::Capsule.Scenes.Spawning.EntityRegistration[]
            {
                new global::Capsule.Scenes.Spawning.EntityRegistration("door", static (global::Capsule.Scenes.Spawning.EntitySpawn spawn) => new global::Game.Door(spawn)),
                new global::Capsule.Scenes.Spawning.EntityRegistration(
                    "floor-switch",
                    static (global::Capsule.Scenes.Spawning.EntitySpawn spawn) => New_Game_FloorSwitch(spawn),
                    Link: static (placed, properties) =>
                    {
                        global::Game.FloorSwitch entity = (global::Game.FloorSwitch)placed;
                        entity.Lamp = properties.Entity<global::Game.Lamp>("lamp");
                    }),
                new global::Capsule.Scenes.Spawning.EntityRegistration(
                    "lamp",
                    static (global::Capsule.Scenes.Spawning.EntitySpawn spawn) => new global::Game.Lamp(spawn),
                    static (placed, properties) =>
                    {
                        global::Game.Lamp entity = (global::Game.Lamp)placed;
                        SetGlow(entity, properties.Name("glow") switch
                        {
                            "dim" => global::Game.Glow.Dim,
                            "bright" => global::Game.Glow.Bright,
                            _ => throw properties.NotAName("glow", "dim, bright"),
                        });
                        if (properties.Has("icon"))
                        {
                            entity.Icon = properties.Texture("icon", FindTexture);
                        }
                        if (properties.Has("charge"))
                        {
                            SetCharge(entity) = properties.Int("charge");
                        }
                    }),
            };

        /// <summary>The registry a scene resolves its spawn types through.</summary>
        public static global::Capsule.Scenes.Spawning.EntityRegistry Registry { get; } =
            new global::Capsule.Scenes.Spawning.EntityRegistry(Registrations);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]
        private static extern global::Game.FloorSwitch New_Game_FloorSwitch(global::Capsule.Scenes.Spawning.EntitySpawn spawn);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Glow")]
        private static extern void SetGlow(global::Game.Lamp owner, global::Game.Glow value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "_charge")]
        private static extern ref int SetCharge(global::Game.Lamp owner);

        private static global::Capsule.Assets.TextureHandle? FindTexture(string key) => key switch
        {
            "textures/lamp.png" => global::Capsule.Generated.Documents.Asset0,
            _ => null,
        };
    }
}
