using Capsule.Levels;
using Capsule.Levels.Cli.Tiled;

namespace Capsule.Tests.Levels;

/// <summary>
/// The importer against the checked-in fixtures. Every rule it enforces exists because the
/// alternative is a level that is silently wrong rather than one that fails to import.
/// </summary>
public sealed class TiledImportTests
{
    // The strong form of the determinism claim: room.level.json was generated by an earlier
    // run in an earlier process, and re-importing must reproduce its bytes exactly. It also
    // pins palette order (tileset then tile id, unpainted classes included), gid 0 as empty,
    // entity pass-through, and the source stamp.
    [Fact]
    public void Import_ReproducesTheCommittedLevelByteForByte()
    {
        string levelPath = LevelFixtures.Path("room.level.json");

        Level level = TiledImporter.Import(LevelFixtures.Path("room.tmj"), levelPath);

        Assert.Equal(File.ReadAllText(levelPath), LevelFile.ToJson(level));
    }

    [Fact]
    public void Import_PutsUnpaintedClassesInThePaletteInTileIdOrder()
    {
        Level level = TiledImporter.Import(LevelFixtures.Path("room.tmj"), LevelFixtures.Path("room.level.json"));

        // "ledge" is defined on tile 2 and painted nowhere: the palette is the tileset's
        // vocabulary, so painting a new type later cannot renumber the types already in use.
        Assert.Equal(["empty", "ground", "wall", "ledge", "hazard"], level.TileTypes.ToArray());
    }

    // Tiled 1.9 wrote "class" and embedded tilesets inline; 1.10 reverted to "type". A map
    // authored in either version must import identically, or the tool version becomes canon.
    [Fact]
    public void Import_ReadsTheClassAndTypeSpellingsAlike()
    {
        Level golden = LevelFile.Load(LevelFixtures.Path("room.level.json"));

        Level level = TiledImporter.Import(
            LevelFixtures.Path("room-tiled19.tmj"),
            LevelFixtures.Path("room-tiled19.level.json"));

        Assert.Equal(golden.TileSize, level.TileSize);
        Assert.Equal(golden.NextEntityId, level.NextEntityId);
        Assert.Equal(golden.TileTypes.ToArray(), level.TileTypes.ToArray());
        Assert.Equal(golden.Tiles.ToArray(), level.Tiles.ToArray());
        Assert.Equal(golden.Entities.ToArray(), level.Entities.ToArray());
    }

    // Path.GetRelativePath hands back backslashes on Windows, and a level file has to mean the
    // same thing on every machine. The golden fixture cannot prove this: its source sits in the
    // same directory, so the stamp carries no separator at all.
    [Fact]
    public void Import_StampsAForwardSlashRelativeSourcePath()
    {
        using LevelFixtures.Workspace workspace = new();
        Directory.CreateDirectory(workspace.Path("maps"));
        File.WriteAllText(workspace.Path("maps/room.tmj"), LevelFixtures.Read("room.tmj"));
        File.WriteAllText(workspace.Path("maps/tiles.tsj"), LevelFixtures.Read("tiles.tsj"));

        Level level = TiledImporter.Import(workspace.Path("maps/room.tmj"), workspace.Path("room.level.json"));

        Assert.Equal("maps/room.tmj", level.Source?.Path);
    }

    [Theory]
    [InlineData("\"orientation\":\"orthogonal\"", "\"orientation\":\"isometric\"", "orthogonal maps only")]
    [InlineData("\"infinite\":false", "\"infinite\":true", "infinite map")]
    [InlineData("\"tileheight\":16", "\"tileheight\":8", "square tiles only")]
    [InlineData("\"type\":\"tilelayer\"", "\"type\":\"imagelayer\"", "unsupported layer type")]
    [InlineData("\"type\":\"objectgroup\"", "\"type\":\"tilelayer\"", "more than one tile layer")]
    [InlineData("\"type\":\"tilelayer\"", "\"type\":\"objectgroup\"", "no tile layer")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 2147483649]", "flipped or rotated")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 5]", "has no Class")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 4, 0]", "requires 12")]
    [InlineData("\"type\":\"coin\"", "\"type\":\"\"", "every object becomes an entity")]
    [InlineData("\"source\":\"tiles.tsj\"", "\"source\":\"tiles.tsx\"", "XML")]
    [InlineData("\"source\":\"tiles.tsj\"", "\"source\":\"missing.tsj\"", "is missing")]
    [InlineData("\"data\":[0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 4],", "\"data\":\"AAAA\",\"encoding\":\"base64\",", "CSV")]
    public void Import_RejectsWhatItCannotRepresent(string from, string to, string expected)
    {
        TiledImportException error = ImportMutated(from, to, mutateTileset: false);

        Assert.Contains(expected, error.Message, StringComparison.Ordinal);
    }

    // Bijectivity: one Class names one tile, so a level's tile type can be turned back into
    // the tile that means it.
    [Fact]
    public void Import_RejectsAClassDefinedByTwoTiles()
    {
        TiledImportException error = ImportMutated("\"type\":\"ledge\"", "\"type\":\"wall\"", mutateTileset: true);

        Assert.Contains("more than one tile", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Import_RejectsAClassThatShadowsTheEmptyTileType()
    {
        TiledImportException error = ImportMutated("\"type\":\"ledge\"", "\"type\":\"empty\"", mutateTileset: true);

        Assert.Contains("reserved", error.Message, StringComparison.Ordinal);
    }

    // Width * Height as an int wraps, and the wrapped value would size the tile array rather
    // than fail. Both the map and its one tile layer carry the dimensions.
    [Fact]
    public void Import_RejectsAGridWhoseAreaOverflowsAnInt()
    {
        string map = Mutate(LevelFixtures.Read("room.tmj"), "\"width\":4", "\"width\":65536");
        map = Mutate(map, "\"height\":3", "\"height\":65536");

        TiledImportException error = Import(map, LevelFixtures.Read("tiles.tsj"));

        Assert.Contains("65536x65536", error.Message, StringComparison.Ordinal);
    }

    private static TiledImportException ImportMutated(string from, string to, bool mutateTileset)
    {
        string map = LevelFixtures.Read("room.tmj");
        string tileset = LevelFixtures.Read("tiles.tsj");

        if (mutateTileset)
        {
            tileset = Mutate(tileset, from, to);
        }
        else
        {
            map = Mutate(map, from, to);
        }

        return Import(map, tileset);
    }

    private static TiledImportException Import(string map, string tileset)
    {
        using LevelFixtures.Workspace workspace = new();
        workspace.Write("tiles.tsj", tileset);
        string mapPath = workspace.Write("room.tmj", map);

        return Assert.Throws<TiledImportException>(
            () => TiledImporter.Import(mapPath, workspace.Path("room.level.json")));
    }

    // A fixture edit must not quietly defang a row of the theory.
    private static string Mutate(string text, string from, string to)
    {
        Assert.Contains(from, text, StringComparison.Ordinal);
        return text.Replace(from, to, StringComparison.Ordinal);
    }
}
