using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Scenes.Generator;

internal enum BootWiring
{
    /// <summary>Nothing to emit: the compilation does not reference the engine host.</summary>
    None,
    Unwired,
    WithScenes,
}

/// <summary>
/// The <c>GameBoot</c> entry point: <c>CapsuleEngine.Configure()</c> already carrying the scene
/// registry generated into the game's logic assembly, read from the shell's referenced metadata.
/// It is emitted wired or unwired, never withheld, so the shell's <c>Program</c> compiles the same
/// whatever the references hold: a shell running a hand-written <c>ISimulation</c> wants no
/// registry, and one that wanted the registry hears about it from the boot verb that needed it.
/// </summary>
internal static class GameBootSource
{
    private const string FileName = "CapsuleGameBoot.g.cs";

    internal static BootWiring Describe(Compilation compilation)
    {
        if (compilation.GetTypeByMetadataName(Symbols.CapsuleEngine) is null)
        {
            return BootWiring.None;
        }

        return compilation.GetTypeByMetadataName(Symbols.GameScenes) is null
            ? BootWiring.Unwired
            : BootWiring.WithScenes;
    }

    internal static void Emit(SourceProductionContext context, BootWiring wiring)
    {
        if (wiring == BootWiring.None)
        {
            return;
        }

        context.AddSource(FileName, SourceText.From(Render(wiring), Encoding.UTF8));
    }

    private static string Render(BootWiring wiring)
    {
        StringBuilder source = new();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Capsule.Runtime.Generated");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>This game's entry point. Generated; do not edit.</summary>");
        source.AppendLine("    public static class GameBoot");
        source.AppendLine("    {");
        source.AppendLine("        /// <summary>The engine, configured with every registry this game generates.</summary>");
        source.AppendLine("        public static global::Capsule.Runtime.EngineBuilder Configure() =>");

        if (wiring == BootWiring.WithScenes)
        {
            source.AppendLine("            global::Capsule.Runtime.CapsuleEngine.Configure()");
            source.AppendLine("                .WithScenes(global::Capsule.Scenes.Generated.GameScenes.Registry);");
        }
        else
        {
            source.AppendLine("            global::Capsule.Runtime.CapsuleEngine.Configure();");
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }
}
