using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Generators;

// Every generated type lives in Capsule.Generated. A compilation that receives any of them imports that
// namespace through CapsuleGlobalUsings.g.cs, and game code writes no using for it.
internal static class GlobalUsingsRenderer
{
    private const string FileName = "CapsuleGlobalUsings.g.cs";

    internal const string Text = "// <auto-generated/>\nglobal using global::Capsule.Generated;\n";

    internal static void Emit(SourceProductionContext context, ProjectConfiguration project)
    {
        if (project.IsLogicAssembly || project.IsShellAssembly)
        {
            context.AddSource(FileName, SourceText.From(Text, Encoding.UTF8));
        }
    }
}
