// <auto-generated/>
#nullable enable

[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryProviderAttribute(typeof(global::Capsule.Generated.CapsuleRegistryProvider_AssetSpecs_F172E44D))]

namespace Capsule.Generated
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class CapsuleGeneratedRegistryProviderAttribute : global::System.Attribute
    {
        public CapsuleGeneratedRegistryProviderAttribute(global::System.Type providerType) => ProviderType = providerType;
        public global::System.Type ProviderType { get; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class CapsuleGeneratedRegistryClaimAttribute : global::System.Attribute
    {
        public CapsuleGeneratedRegistryClaimAttribute(int kind, string key, global::System.Type declaringType)
        {
            Kind = kind;
            Key = key;
            DeclaringType = declaringType;
        }
        public int Kind { get; }
        public string Key { get; }
        public global::System.Type DeclaringType { get; }
    }

    /// <summary>This assembly's registries, read by the shell's generated <c>CapsuleBoot</c> and by <c>CapsuleScenes.Registry</c>. Generated code. Do not edit.</summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CapsuleRegistryProvider_AssetSpecs_F172E44D
    {
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void AddScenes(global::Capsule.Scenes.SceneRegistryBuilder scenes)
        {
            global::System.ArgumentNullException.ThrowIfNull(scenes);
            scenes.AddEntities(global::Capsule.Generated.CapsuleEntities.Registrations);
            scenes.AddScenes(global::Capsule.Generated.CapsuleScenes.Registrations);
            scenes.AddAppliers(global::Capsule.Generated.CapsuleScenes.Appliers);
            scenes.AddTileTypes(global::Capsule.Generated.CapsuleScenes.TileTypes);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static void AddDrivers(global::System.Collections.Generic.List<global::Capsule.Input.InputDriverRegistration> registrations)
        {
            global::System.ArgumentNullException.ThrowIfNull(registrations);
            registrations.AddRange(global::Capsule.Generated.CapsuleInputDrivers.Registrations);
        }
    }
}
