// <auto-generated/>
#nullable enable

namespace Capsule.Generated
{
    /// <summary>This game's entry point. Generated code. Do not edit.</summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CapsuleBoot
    {
        private static global::Capsule.Scenes.SceneRegistry Scenes { get; } = CreateScenes();

        private static global::Capsule.Input.InputDriverRegistry Drivers { get; } = CreateDrivers();

        /// <summary>Begins the engine's configuration with every registry this game generates.</summary>
        /// <param name="gameName">The game's display name. It titles the window, and its slug names the local folder that holds the saves and the crash log.</param>
        /// <param name="platform">The platform module for the host family this shell targets.</param>
        public static global::Capsule.Runtime.EngineBuilder Configure(string gameName, global::Capsule.Runtime.HostPlatform platform) =>
            global::Capsule.Runtime.CapsuleEngine.Configure(gameName, platform, Scenes, Drivers);

        private static global::Capsule.Scenes.SceneRegistry CreateScenes()
        {
            var scenes = new global::Capsule.Scenes.SceneRegistryBuilder();
            global::Capsule.Generated.CapsuleRegistryProvider_GameSpecs_85683739.AddScenes(scenes);
            return scenes.Build();
        }

        private static global::Capsule.Input.InputDriverRegistry CreateDrivers()
        {
            var drivers = new global::System.Collections.Generic.List<global::Capsule.Input.InputDriverRegistration>();
            global::Capsule.Generated.CapsuleRegistryProvider_GameSpecs_85683739.AddDrivers(drivers);
            drivers.Add(new global::Capsule.Input.InputDriverRegistration("Replay", static () => new global::Shell.Replay()));
            return new global::Capsule.Input.InputDriverRegistry(drivers);
        }
    }
}
