// <auto-generated/>
#nullable enable

[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute(1, "scenes/hall", typeof(global::Game.Hall))]

namespace Capsule.Generated
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class CapsuleGeneratedScene_Scenes_Room : global::Game.PlayableScene
    {
        internal CapsuleGeneratedScene_Scenes_Room(global::Capsule.Scenes.SceneContent content) : base(content)
        {
        }
    }

    /// <summary>Every scene this assembly declares. Generated code. Do not edit.</summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CapsuleScenes
    {
        internal static global::Capsule.Scenes.SceneRegistration[] Registrations { get; } =
            new global::Capsule.Scenes.SceneRegistration[]
            {
                global::Capsule.Scenes.SceneRegistration.Plain(typeof(global::Game.MainMenu), static _ => new global::Game.MainMenu()),
                global::Capsule.Scenes.SceneRegistration.FromDocument(typeof(global::Game.Hall), "scenes/hall", static content => new global::Game.Hall(content!.Value with { Camera = static () => new global::Game.GameCamera() })),
                global::Capsule.Scenes.SceneRegistration.DocumentOnly("scenes/room", static content => new global::Capsule.Generated.CapsuleGeneratedScene_Scenes_Room(content!.Value with { Camera = static () => new global::Game.GameCamera() })),
            };

        /// <summary>The registry the engine composes every scene through.</summary>
        public static global::Capsule.Scenes.SceneRegistry Registry { get; } =
            new global::Capsule.Scenes.SceneRegistry(
                global::Capsule.Generated.CapsuleEntities.Registry,
                Registrations);
    }
}
