// <auto-generated/>
#nullable enable

[assembly: global::Capsule.Generated.CapsuleGeneratedRegistryClaimAttribute(1, "scenes/hall", typeof(global::Game.Hall))]

namespace Capsule.Generated
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class CapsuleGeneratedScene_Scenes_Room : global::Game.PlayableScene
    {
        internal CapsuleGeneratedScene_Scenes_Room(global::Capsule.Scenes.SceneContent content) : base(content)
        {
        }
    }

    /// <summary>Every scene this assembly declares. Generated code. Do not edit.</summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class CapsuleScenes
    {
        internal static global::Capsule.Scenes.SceneRegistration[] Registrations { get; } =
            new global::Capsule.Scenes.SceneRegistration[]
            {
                global::Capsule.Scenes.SceneRegistration.Plain(typeof(global::Game.MainMenu), static _ => new global::Game.MainMenu()),
                global::Capsule.Scenes.SceneRegistration.FromDocument(typeof(global::Game.Hall), "scenes/hall", static content => new global::Game.Hall(content!.Value with { Apply = Apply_Capsule_Scenes_Scene, Entities = content!.Value.Entities.OwnedBy(global::Capsule.Generated.CapsuleEntities.Registrations) })),
                global::Capsule.Scenes.SceneRegistration.DocumentOnly("scenes/room", static content => new global::Capsule.Generated.CapsuleGeneratedScene_Scenes_Room(content!.Value with { Apply = Apply_Game_PlayableScene, Entities = content!.Value.Entities.OwnedBy(global::Capsule.Generated.CapsuleEntities.Registrations) })),
            };

        // The applier of each scene class authoring members, by class, which SceneRegistry.Content finds along a class's bases.
        internal static global::System.Collections.Generic.KeyValuePair<global::System.Type, global::Capsule.Scenes.SceneApplier>[] Appliers { get; } =
            new global::System.Collections.Generic.KeyValuePair<global::System.Type, global::Capsule.Scenes.SceneApplier>[]
            {
                new(typeof(global::Capsule.Scenes.Scene), Apply_Capsule_Scenes_Scene),
                new(typeof(global::Game.PlayableScene), Apply_Game_PlayableScene),
            };

        /// <summary>The registry the engine composes every scene through.</summary>
        public static global::Capsule.Scenes.SceneRegistry Registry { get; } = CreateRegistry();

        // Built through the provider the shell's CapsuleBoot reads. A test composing through Registry composes what a run does.
        private static global::Capsule.Scenes.SceneRegistry CreateRegistry()
        {
            var scenes = new global::Capsule.Scenes.SceneRegistryBuilder();
            global::Capsule.Generated.CapsuleRegistryProvider_AssetSpecs_F172E44D.AddScenes(scenes);
            return scenes.Build();
        }

        private static void Apply_Capsule_Scenes_Scene(global::Capsule.Scenes.Scene composed, global::Capsule.Scenes.Spawning.AuthoredMembers members)
        {
            global::Capsule.Scenes.Scene scene = (global::Capsule.Scenes.Scene)composed;
            if (members.Has("camera"))
            {
                SetCamera(scene, Object_Capsule_Scenes_Camera(scene.Camera, members.Object("camera"), replaces: true));
            }
            if (members.Has("size"))
            {
                SetSize(scene, members.Vector2("size"));
            }
            if (members.Has("clearColor"))
            {
                SetClearColor(scene, members.Color("clearColor"));
            }
            if (members.Has("ambient"))
            {
                SetAmbient(scene, members.Color("ambient"));
            }
            if (members.Has("sampling"))
            {
                SetSampling(scene, members.Name("sampling") switch
                {
                    "linear" => global::Capsule.Rendering.TextureSampling.Linear,
                    "point" => global::Capsule.Rendering.TextureSampling.Point,
                    _ => throw members.NotAName("sampling", "linear, point"),
                });
            }
        }

        private static void Apply_Game_PlayableScene(global::Capsule.Scenes.Scene composed, global::Capsule.Scenes.Spawning.AuthoredMembers members)
        {
            global::Game.PlayableScene scene = (global::Game.PlayableScene)composed;
            if (members.Has("camera"))
            {
                SetCamera(scene, Object_Capsule_Scenes_Camera(scene.Camera, members.Object("camera"), replaces: true));
            }
            if (members.Has("size"))
            {
                SetSize(scene, members.Vector2("size"));
            }
            if (members.Has("clearColor"))
            {
                SetClearColor(scene, members.Color("clearColor"));
            }
            if (members.Has("ambient"))
            {
                SetAmbient(scene, members.Color("ambient"));
            }
            if (members.Has("sampling"))
            {
                SetSampling(scene, members.Name("sampling") switch
                {
                    "linear" => global::Capsule.Rendering.TextureSampling.Linear,
                    "point" => global::Capsule.Rendering.TextureSampling.Point,
                    _ => throw members.NotAName("sampling", "linear, point"),
                });
            }
            if (members.Has("floor"))
            {
                SetFloor(scene, members.Int("floor"));
            }
        }

        private static global::Capsule.Scenes.Camera Object_Capsule_Scenes_Camera(global::Capsule.Scenes.Camera? held, global::Capsule.Scenes.Spawning.AuthoredMembers members, bool replaces) => (replaces ? members.Type() : null) switch
        {
            null => held switch
            {
                global::Game.GameCamera subclass => Fill_Game_GameCamera(subclass, members),
                null => Fill_Capsule_Scenes_Camera(new global::Capsule.Scenes.Camera(), members),
                _ => Fill_Capsule_Scenes_Camera(held, members),
            },
            "game-camera" => Fill_Game_GameCamera(new global::Game.GameCamera(), members),
            _ => throw members.NotAType("game-camera"),
        };

        private static global::Capsule.Scenes.Camera Fill_Capsule_Scenes_Camera(global::Capsule.Scenes.Camera target, global::Capsule.Scenes.Spawning.AuthoredMembers members)
        {
            if (members.Has("scrollCenter"))
            {
                target.ScrollCenter = members.IsNull("scrollCenter") ? null : members.Vector2("scrollCenter");
            }
            return target;
        }

        private static global::Game.GameCamera Fill_Game_GameCamera(global::Game.GameCamera target, global::Capsule.Scenes.Spawning.AuthoredMembers members)
        {
            if (members.Has("scrollCenter"))
            {
                target.ScrollCenter = members.IsNull("scrollCenter") ? null : members.Vector2("scrollCenter");
            }
            return target;
        }

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Camera")]
        private static extern void SetCamera(global::Capsule.Scenes.Scene owner, global::Capsule.Scenes.Camera value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Size")]
        private static extern void SetSize(global::Capsule.Scenes.Scene owner, global::System.Numerics.Vector2 value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_ClearColor")]
        private static extern void SetClearColor(global::Capsule.Scenes.Scene owner, global::Capsule.Rendering.ColorRgba value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Ambient")]
        private static extern void SetAmbient(global::Capsule.Scenes.Scene owner, global::Capsule.Rendering.ColorRgba value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Sampling")]
        private static extern void SetSampling(global::Capsule.Scenes.Scene owner, global::Capsule.Rendering.TextureSampling value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Floor")]
        private static extern void SetFloor(global::Game.PlayableScene owner, int value);
    }
}
