using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Capsule.Scenes.Generator;

internal static class RegistryProviderSource
{
    private const string FileName = "CapsuleRegistryProvider.g.cs";

    internal static void Emit(SourceProductionContext context, string? providerName)
    {
        if (providerName is not null)
        {
            context.AddSource(FileName, SourceText.From(Render(providerName), Encoding.UTF8));
        }
    }

    private static string Render(string providerName)
    {
        StringBuilder source = new();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("[assembly: global::Capsule.Scenes.Generated.CapsuleGeneratedRegistryProviderAttribute(typeof(global::Capsule.Scenes.Generated.");
        source.Append(providerName);
        source.AppendLine("))]");
        source.AppendLine();
        source.AppendLine("namespace Capsule.Scenes.Generated");
        source.AppendLine("{");
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        source.AppendLine("    internal sealed class CapsuleGeneratedRegistryProviderAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public CapsuleGeneratedRegistryProviderAttribute(global::System.Type providerType) => ProviderType = providerType;");
        source.AppendLine("        public global::System.Type ProviderType { get; }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        source.AppendLine("    internal sealed class CapsuleGeneratedRegistryClaimAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public CapsuleGeneratedRegistryClaimAttribute(int kind, string key, global::System.Type declaringType)");
        source.AppendLine("        {");
        source.AppendLine("            Kind = kind;");
        source.AppendLine("            Key = key;");
        source.AppendLine("            DeclaringType = declaringType;");
        source.AppendLine("        }");
        source.AppendLine("        public int Kind { get; }");
        source.AppendLine("        public string Key { get; }");
        source.AppendLine("        public global::System.Type DeclaringType { get; }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        source.Append("    public static class ");
        source.AppendLine(providerName);
        source.AppendLine("    {");
        source.AppendLine("        public static void AddEntities(global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::Capsule.Scenes.Spawning.EntitySpawner>> registrations)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(registrations);");
        source.AppendLine("            registrations.AddRange(global::Capsule.Scenes.Generated.GameEntities.Registrations);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public static void AddScenes(global::System.Collections.Generic.List<global::Capsule.Scenes.SceneRegistration> registrations)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(registrations);");
        source.AppendLine("            registrations.AddRange(global::Capsule.Scenes.Generated.GameScenes.Registrations);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }
}
