using Capsule.Maps;
using Capsule.Maps.Cli.Tiled;
using Capsule.Rendering;

namespace Capsule.Tests.Maps;

/// <summary>
/// The importer against the checked-in fixtures. Every rule it enforces exists because the
/// alternative is a map that is silently wrong rather than one that fails to import.
/// </summary>
[Collection(MapWorkspaceCollection.Name)]
public sealed class TiledImportTests
{
    // The strong form of the determinism claim: room.map.json was generated by an earlier run
    // in an earlier process, and re-importing must reproduce its bytes exactly. It also pins
    // palette order (tileset then tile id, unpainted classes included), gid 0 as empty, object
    // pass-through, and the source stamp.
    [Fact]
    public void Import_ReproducesTheCommittedMapByteForByte()
    {
        using MapFixtures.Workspace workspace = MapFixtures.CopyMaps("room");

        Map map = TiledImporter.Import("room.tmj");

        Assert.Equal(MapFixtures.Read("room.map.json"), MapFile.ToJson(map));
    }

    [Fact]
    public void Import_PutsUnpaintedClassesInThePaletteInTileIdOrder()
    {
        using MapFixtures.Workspace workspace = MapFixtures.CopyMaps("room");

        Map map = TiledImporter.Import("room.tmj");

        // "ledge" is defined on tile 2 and painted nowhere: the palette is the tileset's
        // vocabulary, so painting a new type later cannot renumber the types already in use.
        string[] types = [.. map.Grid.TileTypes.ToArray().Select(static definition => definition.Type)];

        Assert.Equal(["empty", "ground", "wall", "ledge", "hazard"], types);
    }

    // Tiled writes a colour property as #AARRGGBB, alpha first and optional, in either case;
    // the map format's colour is #rrggbbaa. A channel swap here would still produce a plausible
    // colour, so the fixture's "ledge" is the witness — every one of its four channels differs.
    [Theory]
    [InlineData("#cc718096", 0x71, 0x80, 0x96, 0xCC)]
    [InlineData("#CC718096", 0x71, 0x80, 0x96, 0xCC)]
    [InlineData("#718096", 0x71, 0x80, 0x96, 0xFF)]
    public void Import_ReordersTiledsAlphaFirstColourIntoRgba(string authored, int r, int g, int b, int a)
    {
        string tileset = Mutate(MapFixtures.Read("tiles.tsj"), "\"#cc718096\"", $"\"{authored}\"");

        using MapFixtures.Workspace workspace = new();
        workspace.Write("tiles.tsj", tileset);
        string mapPath = workspace.Write("room.tmj", MapFixtures.Read("room.tmj"));

        Map map = TiledImporter.Import(mapPath);

        Assert.Equal(new ColorRgba((byte)r, (byte)g, (byte)b, (byte)a), map.Grid.TileTypes[3].Color);
    }

    // Class is semantic identity; colour is only the current presentation lane and may be
    // absent when another renderer will present the tile.
    [Fact]
    public void Import_AcceptsATileClassWithNoColourProperty()
    {
        string tileset = Mutate(MapFixtures.Read("tiles.tsj"), "\"name\":\"color\"", "\"name\":\"colour\"");
        using MapFixtures.Workspace workspace = new();
        workspace.Write("tiles.tsj", tileset);

        Map map = TiledImporter.Import(workspace.Write("room.tmj", MapFixtures.Read("room.tmj")));

        Assert.Null(map.Grid.TileTypes[1].Color);
        Assert.Equal("ground", map.Grid.TileTypes[1].Type);
    }

    [Fact]
    public void Import_RejectsAColourPropertyTiledCouldNotHaveWritten()
    {
        TiledImportException error = ImportMutated("\"#ff2d3748\"", "\"slate\"", mutateTileset: true);

        Assert.Contains("not a Tiled colour", error.Message, StringComparison.Ordinal);
    }

    // A string property spelled '#aarrggbb' is the same characters as a Color one, so the
    // declared type is all that separates the contract from a tileset that looks authored. An
    // omitted type is the second row because Tiled writes none for a string property.
    [Theory]
    [InlineData("\"type\":\"string\",")]
    [InlineData("")]
    public void Import_RejectsAColourPropertyNotDeclaredAsAColour(string declaredType)
    {
        TiledImportException error = ImportMutated("\"type\":\"color\",", declaredType, mutateTileset: true);

        Assert.Contains("tileset 'terrain' tile 0", error.Message, StringComparison.Ordinal);
        Assert.Contains("Class 'ground'", error.Message, StringComparison.Ordinal);
        Assert.Contains("as a 'string' property", error.Message, StringComparison.Ordinal);
    }

    // A game declares one tile size and every map is checked against it during the build, so a
    // wrong Tile Width in Tiled fails there rather than at boot.
    [Fact]
    public void Import_RejectsAMapWhoseTileSizeIsNotTheDeclaredOne()
    {
        using MapFixtures.Workspace workspace = MapFixtures.CopyMaps("room");

        TiledImportException error = Assert.Throws<TiledImportException>(
            () => TiledImporter.Import("room.tmj", tileSize: 8));

        Assert.Contains("has 16px tiles", error.Message, StringComparison.Ordinal);
        Assert.Contains("declares 8px", error.Message, StringComparison.Ordinal);
    }

    // Capsule holds no opinion on tile size: declare none and each map keeps its own, so a game
    // that deliberately mixes them is not boxed in.
    [Fact]
    public void Import_WithNoDeclaredTileSize_TakesTheMapsOwn()
    {
        string map = Mutate(MapFixtures.Read("room.tmj"), "\"tileheight\":16", "\"tileheight\":8");
        map = Mutate(map, "\"tilewidth\":16", "\"tilewidth\":8");

        using MapFixtures.Workspace workspace = new();
        workspace.Write("tiles.tsj", MapFixtures.Read("tiles.tsj"));

        Assert.Equal(8, TiledImporter.Import(workspace.Write("room.tmj", map)).Grid.TileSize);
    }

    // Tiled 1.9 wrote "class" and embedded tilesets inline; 1.10 reverted to "type". A source
    // authored in either version must import identically, or the tool version becomes canon.
    [Fact]
    public void Import_ReadsTheClassAndTypeSpellingsAlike()
    {
        Map golden = MapFile.Load(MapFixtures.Path("room.map.json"));
        using MapFixtures.Workspace workspace = new();

        Map map = TiledImporter.Import(
            workspace.Write("room-tiled19.tmj", MapFixtures.Read("room-tiled19.tmj")));

        Assert.Equal(golden.Grid.TileSize, map.Grid.TileSize);
        Assert.Equal(golden.NextObjectId, map.NextObjectId);
        Assert.Equal(golden.Grid.TileTypes.ToArray(), map.Grid.TileTypes.ToArray());
        Assert.Equal(golden.Grid.Tiles.ToArray(), map.Grid.Tiles.ToArray());
        Assert.Equal(golden.Objects.ToArray(), map.Objects.ToArray());
    }

    // The stamp is the path as given, and Windows hands back backslashes from anything that
    // composes one — while a map file has to mean the same thing on every machine. The golden
    // fixture cannot prove this: its source sits in the working directory, so the stamp carries
    // no separator at all.
    [Fact]
    public void Import_ForwardSlashesTheSourcePathItStamps()
    {
        using MapFixtures.Workspace workspace = MapFixtures.CopyMaps("maps/room");

        Map map = TiledImporter.Import(Path.Combine("maps", "room.tmj"));

        Assert.Equal("maps/room.tmj", map.Source?.Path);
    }

    [Fact]
    public void Import_SourceHashChangesWhenAnExternalTilesetChanges()
    {
        using MapFixtures.Workspace workspace = new();
        workspace.Write("room.tmj", MapFixtures.Read("room.tmj"));
        workspace.Write("tiles.tsj", MapFixtures.Read("tiles.tsj"));
        string first = TiledImporter.Import("room.tmj").Source!.Value.Hash;

        string changed = Mutate(MapFixtures.Read("tiles.tsj"), "#ff4a5568", "#ff4a5569");
        workspace.Write("tiles.tsj", changed);
        string second = TiledImporter.Import("room.tmj").Source!.Value.Hash;

        Assert.NotEqual(first, second);
    }

    [Fact]
    public void Import_AcceptsAnExternalTilesetWithinTheTrackedRoot()
    {
        using MapFixtures.Workspace workspace = new();
        Directory.CreateDirectory("assets/maps");
        workspace.Write("assets/tiles.tsj", MapFixtures.Read("tiles.tsj"));
        string map = Mutate(MapFixtures.Read("room.tmj"), "\"source\":\"tiles.tsj\"", "\"source\":\"../tiles.tsj\"");
        workspace.Write("assets/maps/room.tmj", map);

        Map imported = TiledImporter.Import("assets/maps/room.tmj", dependencyRoot: "assets");

        Assert.Equal("ground", imported.Grid.TileTypes[1].Type);
    }

    [Fact]
    public void Import_RejectsAnExternalTilesetOutsideTheTrackedRoot()
    {
        using MapFixtures.Workspace workspace = new();
        Directory.CreateDirectory("assets/maps");
        workspace.Write("tiles.tsj", MapFixtures.Read("tiles.tsj"));
        string map = Mutate(MapFixtures.Read("room.tmj"), "\"source\":\"tiles.tsj\"", "\"source\":\"../../tiles.tsj\"");
        workspace.Write("assets/maps/room.tmj", map);

        TiledImportException error = Assert.Throws<TiledImportException>(
            () => TiledImporter.Import("assets/maps/room.tmj", dependencyRoot: "assets"));

        Assert.Contains("outside the tracked asset source root", error.Message, StringComparison.Ordinal);
    }

    // The stamp is provenance somebody else has to be able to follow, so an absolute path is
    // refused at the format rather than written and shrugged at. Naming the sources relatively
    // is the invoker's job — the build hook runs the tool from the shell project to discharge it.
    [Fact]
    public void Import_RefusesAnAbsoluteSourcePath()
    {
        using MapFixtures.Workspace workspace = MapFixtures.CopyMaps("room");

        TiledImportException error = Assert.Throws<TiledImportException>(
            () => TiledImporter.Import(Path.GetFullPath("room.tmj")));

        Assert.Contains("must be relative", error.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("\"orientation\":\"orthogonal\"", "\"orientation\":\"isometric\"", "orthogonal maps only")]
    [InlineData("\"infinite\":false", "\"infinite\":true", "infinite map")]
    [InlineData("\"tileheight\":16", "\"tileheight\":8", "square tiles only")]
    [InlineData("\"type\":\"tilelayer\"", "\"type\":\"imagelayer\"", "unsupported layer type")]
    [InlineData("\"type\":\"objectgroup\"", "\"type\":\"tilelayer\"", "more than one tile layer")]
    [InlineData("\"type\":\"tilelayer\"", "\"type\":\"objectgroup\"", "no tile layer")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 2147483649]", "flipped or rotated")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 5]", "has no Class")]
    [InlineData("1, 1, 1, 4]", "1, 1, 1, 4, 0]", "requires 12")]
    [InlineData("\"type\":\"coin\"", "\"type\":\"\"", "typed by its Class")]
    [InlineData("\"source\":\"tiles.tsj\"", "\"source\":\"tiles.tsx\"", "XML")]
    [InlineData("\"source\":\"tiles.tsj\"", "\"source\":\"missing.tsj\"", "is missing")]
    [InlineData("\"data\":[0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 4],", "\"data\":\"AAAA\",\"encoding\":\"base64\",", "CSV")]
    public void Import_RejectsWhatItCannotRepresent(string from, string to, string expected)
    {
        TiledImportException error = ImportMutated(from, to, mutateTileset: false);

        Assert.Contains(expected, error.Message, StringComparison.Ordinal);
    }

    // Bijectivity: one Class names one tile, so a map's tile type can be turned back into the
    // tile that means it.
    [Fact]
    public void Import_RejectsAClassDefinedByTwoTiles()
    {
        TiledImportException error = ImportMutated("\"type\":\"ledge\"", "\"type\":\"wall\"", mutateTileset: true);

        Assert.Contains("more than one tile", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Import_RejectsAClassThatShadowsTheEmptyTileType()
    {
        TiledImportException error = ImportMutated("\"type\":\"ledge\"", "\"type\":\"empty\"", mutateTileset: true);

        Assert.Contains("reserved", error.Message, StringComparison.Ordinal);
    }

    // Width * Height as an int wraps, and the wrapped value would size the tile array rather
    // than fail. Both the source and its one tile layer carry the dimensions.
    [Fact]
    public void Import_RejectsAGridWhoseAreaOverflowsAnInt()
    {
        string map = Mutate(MapFixtures.Read("room.tmj"), "\"width\":4", "\"width\":65536");
        map = Mutate(map, "\"height\":3", "\"height\":65536");

        TiledImportException error = Import(map, MapFixtures.Read("tiles.tsj"));

        Assert.Contains("65536x65536", error.Message, StringComparison.Ordinal);
    }

    private static TiledImportException ImportMutated(string from, string to, bool mutateTileset)
    {
        string map = MapFixtures.Read("room.tmj");
        string tileset = MapFixtures.Read("tiles.tsj");

        if (mutateTileset)
        {
            tileset = Mutate(tileset, from, to);
        }
        else
        {
            map = Mutate(map, from, to);
        }

        return Import(map, tileset);
    }

    private static TiledImportException Import(string map, string tileset)
    {
        using MapFixtures.Workspace workspace = new();
        workspace.Write("tiles.tsj", tileset);
        string mapPath = workspace.Write("room.tmj", map);

        return Assert.Throws<TiledImportException>(() => TiledImporter.Import(mapPath));
    }

    // A fixture edit must not quietly defang a row of the theory.
    private static string Mutate(string text, string from, string to)
    {
        Assert.Contains(from, text, StringComparison.Ordinal);
        return text.Replace(from, to, StringComparison.Ordinal);
    }
}
